name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        
    - name: Install tmux
      run: sudo apt-get update && sudo apt-get install -y tmux
        
    - name: Run unit tests
      run: go test -v ./internal/server/... ./internal/client/... ./internal/tmux/...
      
    - name: Run integration tests
      run: go test -v ./internal/testing/...
      
    - name: Build
      run: go build -v ./...

  release:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        
    - name: Install svu
      run: |
        wget -O svu.tar.gz https://github.com/caarlos0/svu/releases/download/v1.12.0/svu_1.12.0_linux_amd64.tar.gz
        tar -xzf svu.tar.gz
        sudo mv svu /usr/local/bin/
        
    - name: Check for new version
      id: version
      run: |
        CURRENT=$(git tag --list | grep -E '^v[0-9]+' | sort -V | tail -n1 || echo "")
        NEXT=$(svu next --strip-prefix)
        echo "current=${CURRENT}" >> $GITHUB_OUTPUT
        echo "next=v${NEXT}" >> $GITHUB_OUTPUT
        echo "should_release=$([[ "${CURRENT}" != "v${NEXT}" ]] && echo "true" || echo "false")" >> $GITHUB_OUTPUT
        
    - name: Create release
      if: steps.version.outputs.should_release == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Build binaries for multiple platforms
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o tmux-mcp-server-linux-amd64 ./cmd/tmux-mcp-server
        GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o tmux-mcp-server-linux-arm64 ./cmd/tmux-mcp-server
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o tmux-mcp-server-darwin-amd64 ./cmd/tmux-mcp-server
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o tmux-mcp-server-darwin-arm64 ./cmd/tmux-mcp-server
        
        # Create GitHub release
        gh release create ${{ steps.version.outputs.next }} \
          --title "Release ${{ steps.version.outputs.next }}" \
          --notes "Automated release created from commit ${{ github.sha }}" \
          tmux-mcp-server-linux-amd64 \
          tmux-mcp-server-linux-arm64 \
          tmux-mcp-server-darwin-amd64 \
          tmux-mcp-server-darwin-arm64
